if vim.g.colors_name == 'nazgul' then
  return
end

if vim.g.colors_name then
  vim.cmd 'hi clear'
  vim.cmd 'syntax reset'
end

vim.g.colors_name = 'nazgul'

local set_hl = vim.api.nvim_set_hl

set_hl(0, 'Normal', { fg = '#c6c6c6', bg = '#141414' })
set_hl(0, 'Constant', { fg = '#727272', bold = true })
set_hl(0, 'String', { fg = '#aaaaaa' })
set_hl(0, 'Number', { fg = '#828282' })
set_hl(0, 'NormalFloat', { fg = '#c6c6c6', bg = '#1d1d1d' })
set_hl(0, 'FloatBorder', { fg = '#c6c6c6', bg = '#141414' })
set_hl(0, 'Identifier', { fg = '#969696' })
set_hl(0, 'Function', { fg = '#969696' })
set_hl(0, 'Statement', { fg = '#727272', bold = true })
set_hl(0, 'Operator', { fg = '#d0d0d0' })
set_hl(0, 'Keyword', { fg = '#d0d0d0' })
set_hl(0, 'PreProc', { fg = '#8c8c8c' })
set_hl(0, 'Type', { fg = '#c6c6c6', bold = true })
set_hl(0, 'Special', { fg = '#727272' })
set_hl(0, 'SpecialComment', { fg = '#aaaaaa', bold = true })
set_hl(0, 'Title', { fg = '#8c8c8c', bold = true })
set_hl(0, 'Comment', { fg = '#aaaaaa', italic = true })
set_hl(0, 'LineNr', { fg = '#666666', bg = '#141414' })
set_hl(0, 'FoldColumn', { fg = '#8c8c8c', bg = '#141414' })
set_hl(0, 'CursorLine', { bg = '#282828' })
set_hl(0, 'CursorLineNr', { fg = '#d3d3d3', bg = '#282828' })
set_hl(0, 'Visual', { fg = '#282828', bg = '#828282' })
set_hl(0, 'Search', { fg = '#333333', bg = '#b5b5b5' })
set_hl(0, 'IncSearch', { fg = '#282828', bg = '#8c8c8c', bold = true })
set_hl(0, 'SpellBad', { fg = '#870000', undercurl = true })
set_hl(0, 'SpellCap', { fg = '#870000', undercurl = true })
set_hl(0, 'SpellLocal', { fg = '#870000', undercurl = true })
set_hl(0, 'SpellRare', { fg = '#875f00', undercurl = true })
set_hl(0, 'Error', { fg = '#870000', bold = true })
set_hl(0, 'ErrorMsg', { fg = '#870000' })
set_hl(0, 'WarningMsg', { fg = '#875f00' })
set_hl(0, 'ModeMsg', { fg = '#aaaaaa' })
set_hl(0, 'MoreMsg', { fg = '#aaaaaa' })
set_hl(0, 'Cursor', { bg = '#bfbfbf' })
set_hl(0, 'Underlined', { fg = '#969696', underline = true })
set_hl(0, 'SpecialKey', { fg = '#666666' })
set_hl(0, 'NonText', { fg = '#666666' })
set_hl(0, 'Directory', { fg = '#969696' })
set_hl(0, 'Pmenu', { fg = '#aaaaaa', bg = '#222222' })
set_hl(0, 'PmenuSbar', { fg = '#282828', bg = '#efefef' })
set_hl(0, 'PmenuSel', { fg = '#5b5b5b', bg = '#5b5b5b' })
set_hl(0, 'PmenuThumb', { fg = '#5b5b5b', bg = '#a0a0a0' })
set_hl(0, 'StatusLine', { fg = '#b5b5b5', bg = '#333333' })
set_hl(0, 'StatusLineNC', { fg = '#666666', bg = '#222222' })
set_hl(0, 'WildMenu', { fg = '#969696' })
set_hl(0, 'VertSplit', { fg = '#5b5b5b', bg = '#5b5b5b' })
set_hl(0, 'DiffAdd', { fg = '#141414', bg = '#00875f' })
set_hl(0, 'DiffChange', { fg = '#141414', bg = '#005f87' })
set_hl(0, 'DiffDelete', { fg = '#141414', bg = '#870000' })
set_hl(0, 'DiffText', { fg = '#282828', bg = '#00afff' })
set_hl(0, 'DiffAdded', { fg = '#00875f' })
set_hl(0, 'DiffChanged', { fg = '#005f87' })
set_hl(0, 'DiffRemoved', { fg = '#870000' })
set_hl(0, 'Character', { link = 'Constant' })
set_hl(0, 'Float', { link = 'Number' })
set_hl(0, 'Boolean', { link = 'Number' })
set_hl(0, 'SignColumn', { link = 'FoldColumn' })
set_hl(0, 'ColorColumn', { link = 'FoldColumn' })
set_hl(0, 'CursorColumn', { link = 'CursorLine' })
set_hl(0, 'Folded', { link = 'LineNr' })
set_hl(0, 'Conceal', { link = 'Normal' })
set_hl(0, 'ErrorMsg', { link = 'Error' })
set_hl(0, 'Conditional', { link = 'Statement' })
set_hl(0, 'Repeat', { link = 'Statement' })
set_hl(0, 'Label', { link = 'Statement' })
set_hl(0, 'Exception', { link = 'Statement' })
set_hl(0, 'Include', { link = 'PreProc' })
set_hl(0, 'Define', { link = 'PreProc' })
set_hl(0, 'Macro', { link = 'PreProc' })
set_hl(0, 'PreCondit', { link = 'PreProc' })
set_hl(0, 'StorageClass', { link = 'Type' })
set_hl(0, 'Structure', { link = 'Type' })
set_hl(0, 'Typedef', { link = 'Type' })
set_hl(0, 'SpecialChar', { link = 'Special' })
set_hl(0, 'Tag', { link = 'Special' })
set_hl(0, 'Delimiter', { link = 'Special' })
set_hl(0, 'Debug', { link = 'Special' })
set_hl(0, 'Question', { link = 'Special' })
set_hl(0, 'VisualNOS', { link = 'Visual' })
set_hl(0, 'TabLine', { link = 'StatusLineNC' })
set_hl(0, 'TabLineFill', { link = 'StatusLineNC' })
set_hl(0, 'TabLineSel', { link = 'StatusLine' })
set_hl(0, 'RedSign', { fg = '#cc241d', bg = '#141414' })
set_hl(0, 'YellowSign', { fg = '#fabd2f', bg = '#141414' })
set_hl(0, 'GreenSign', { fg = '#b8cc26', bg = '#141414' })
set_hl(0, 'BlueSign', { fg = '#83a5cb', bg = '#141414' })
set_hl(0, 'AquaSign', { fg = '#8ec07c', bg = '#141414' })
set_hl(0, 'RedHover', { fg = '#cc241d' })
set_hl(0, 'YellowHover', { fg = '#fabd2f' })
set_hl(0, 'OrangeHover', { fg = '#fd7d2f' })
set_hl(0, 'GreenHover', { fg = '#b8cc26' })
set_hl(0, 'BlueHover', { fg = '#83a5cb' })
set_hl(0, 'AquaHover', { fg = '#8ec07c' })
set_hl(0, 'WhiteHover', { fg = '#ffffff' })
set_hl(0, 'Todo', { fg = '#eaeaea', bold = true })
set_hl(0, 'MatchParen', { link = 'Todo' })
set_hl(0, 'DiffAdded', { link = 'GreenSign' })
set_hl(0, 'DiffChanged', { link = 'BlueSign' })
set_hl(0, 'DiffRemoved', { link = 'RedSign' })
set_hl(0, 'SpellBad', { link = 'RedSign' })
set_hl(0, 'Error', { link = 'RedSign' })
set_hl(0, 'ErrorMsg', { link = 'RedSign' })
set_hl(0, 'YellowFloat', { fg = '#cccc00', bg = '#282828' })
set_hl(0, 'CmpItemAbbrDeprecated', { strikethrough = true, fg = '#808080' })
set_hl(0, 'CmpItemAbbrMatch', { fg = '#569CD6' })
set_hl(0, 'CmpItemAbbrMatchFuzzy', { fg = '#569CD6' })
set_hl(0, 'CmpItemKindClass', { fg = '#EE9D28' })
set_hl(0, 'CmpItemKindConstructor', { fg = '#B180D7' })
set_hl(0, 'CmpItemKindEnum', { fg = '#EE9D28' })
set_hl(0, 'CmpItemKindEnumMember', { fg = '#75BEFF' })
set_hl(0, 'CmpItemKindEvent', { fg = '#EE9D28' })
set_hl(0, 'CmpItemKindField', { fg = '#75BEFF' })
set_hl(0, 'CmpItemKindFile', { fg = '#8ec07c' })
set_hl(0, 'CmpItemKindFolder', { fg = '#8ec07c' })
set_hl(0, 'CmpItemKindFunction', { fg = '#B180D7' })
set_hl(0, 'CmpItemKindInterface', { fg = '#75BEFF' })
set_hl(0, 'CmpItemKindKeyword', { fg = '#D4D4D4' })
set_hl(0, 'CmpItemKindMethod', { fg = '#B180D7' })
set_hl(0, 'CmpItemKindModule', { fg = '#fabd2f' })
set_hl(0, 'CmpItemKindNamespace', { fg = '#fabd2f' })
set_hl(0, 'CmpItemKindOperator', { fg = '#D4D4D4' })
set_hl(0, 'CmpItemKindProperty', { fg = '#D4D4D4' })
set_hl(0, 'CmpItemKindPackage', { fg = '#fabd2f' })
set_hl(0, 'CmpItemKindSnippet', { fg = '#fe8019' })
set_hl(0, 'CmpItemKindStruct', { fg = '#EE9D28' })
set_hl(0, 'CmpItemKindTypeParameter', { fg = '#870000' })
set_hl(0, 'CmpItemKindVariable', { fg = '#75BEFF' })
set_hl(0, 'CmpItemMenu', { fg = '#bfbfbf', italic = true })
set_hl(0, 'TSParameter', { italic = true, fg = '#969696' })
set_hl(0, 'DiagnosticError', { link = 'RedHover' })
set_hl(0, 'DiagnosticWarning', { link = 'YellowHover' })
set_hl(0, 'DiagnosticInfo', { link = 'BlueHover' })
set_hl(0, 'DiagnosticHint', { link = 'AquaHover' })
set_hl(0, 'LspReferenceText', { link = 'Todo' })
set_hl(0, 'LspReferenceRead', { link = 'Todo' })
set_hl(0, 'LspReferenceWrite', { link = 'Todo' })
set_hl(0, 'TSDefinition', { link = 'LspReferenceText' })
set_hl(0, 'TSDefinitionUsage', { link = 'LspReferenceWrite' })
set_hl(0, 'LspFloatWinBorder', { link = 'IndentBlanklineChar' })
set_hl(0, 'DiagnosticUnderlineError', { fg = '#ff727b', sp = '#9d0006' })
set_hl(0, 'DiagnosticUnderlineWarn', { fg = '#fabd2f', sp = '#b57614' })
set_hl(0, 'DiagnosticUnderlineInfo', { fg = '#83a598' })
set_hl(0, 'DiagnosticUnderlineHint', { fg = '#83a5cb', sp = '#83a5cb' })
set_hl(0, 'WinSeparator', { bg = '#141414', fg = '#c6c6c6' })
set_hl(0, 'IndentBlanklineContextChar', { fg = '#ffffff' })
-- set_hl(0, 'IndentBlanklineContextStart', {fg='#ffffff', underline=true})
set_hl(0, '@comment', { link = 'Comment' })
set_hl(0, '@none', { bg = 'NONE', fg = 'NONE' })
set_hl(0, '@preproc', { link = 'PreProc' })
set_hl(0, '@define', { link = 'Define' })
set_hl(0, '@operator', { link = 'Operator' })
set_hl(0, '@punctuation.delimiter', { link = 'Delimiter' })
set_hl(0, '@punctuation.bracket', { link = 'Delimiter' })
set_hl(0, '@punctuation.special', { link = 'Delimiter' })
set_hl(0, '@string', { link = 'String' })
set_hl(0, '@string.regex', { link = 'String' })
set_hl(0, '@string.escape', { link = 'SpecialChar' })
set_hl(0, '@string.special', { link = 'SpecialChar' })
set_hl(0, '@character', { link = 'Character' })
set_hl(0, '@character.special', { link = 'SpecialChar' })
set_hl(0, '@boolean', { link = 'Boolean' })
set_hl(0, '@number', { link = 'Number' })
set_hl(0, '@float', { link = 'Float' })
set_hl(0, '@function', { link = 'Function' })
set_hl(0, '@function.call', { link = 'Function' })
set_hl(0, '@function.builtin', { link = 'Special' })
set_hl(0, '@function.macro', { link = 'Macro' })
set_hl(0, '@method', { link = 'Function' })
set_hl(0, '@method.call', { link = 'Function' })
set_hl(0, '@constructor', { link = 'Special' })
set_hl(0, '@parameter', { link = 'Identifier' })
set_hl(0, '@keyword', { link = 'Keyword' })
set_hl(0, '@keyword.function', { link = 'Keyword' })
set_hl(0, '@keyword.return', { link = 'Keyword' })
set_hl(0, '@conditional', { link = 'Conditional' })
set_hl(0, '@repeat', { link = 'Repeat' })
set_hl(0, '@debug', { link = 'Debug' })
set_hl(0, '@label', { link = 'Label' })
set_hl(0, '@include', { link = 'Include' })
set_hl(0, '@exception', { link = 'Exception' })
set_hl(0, '@type', { link = 'Type' })
set_hl(0, '@type.builtin', { link = 'Type' })
set_hl(0, '@type.qualifier', { link = 'Type' })
set_hl(0, '@type.definition', { link = 'Typedef' })
set_hl(0, '@storageclass', { link = 'StorageClass' })
set_hl(0, '@attribute', { link = 'PreProc' })
set_hl(0, '@field', { link = 'Identifier' })
set_hl(0, '@property', { link = 'Identifier' })
set_hl(0, '@variable', { link = 'Identifier' })
set_hl(0, '@variable.builtin', { link = 'Special' })
set_hl(0, '@constant', { link = 'Constant' })
set_hl(0, '@constant.builtin', { link = 'Special' })
set_hl(0, '@constant.macro', { link = 'Define' })
set_hl(0, '@namespace', { link = 'Include' })
set_hl(0, '@symbol', { link = 'Identifier' })
set_hl(0, '@text', { link = 'Normal' })
set_hl(0, '@text.title', { link = 'Title' })
set_hl(0, '@text.literal', { link = 'String' })
set_hl(0, '@text.uri', { link = 'Underlined' })
set_hl(0, '@text.math', { link = 'Special' })
set_hl(0, '@text.environment', { link = 'Macro' })
set_hl(0, '@text.environment.name', { link = 'Type' })
set_hl(0, '@text.reference', { link = 'Constant' })
set_hl(0, '@text.todo', { link = 'Todo' })
set_hl(0, '@text.todo.unchecked', { link = 'Todo' })
set_hl(0, '@text.todo.checked', { link = 'Done' })
set_hl(0, '@text.note', { link = 'SpecialComment' })
set_hl(0, '@text.warning', { link = 'WarningMsg' })
set_hl(0, '@text.danger', { link = 'ErrorMsg' })
set_hl(0, '@text.diff.add', { link = 'diffAdded' })
set_hl(0, '@text.diff.delete', { link = 'diffRemoved' })
set_hl(0, '@tag', { link = 'Tag' })
set_hl(0, '@tag.attribute', { link = 'Identifier' })
set_hl(0, '@tag.delimiter', { link = 'Delimiter' })
set_hl(0, '@text.strong', { bold = true })
set_hl(0, '@text.strike', { strikethrough = true })
set_hl(0, '@text.emphasis', { italic = true })
set_hl(0, '@text.underline', { underline = true })
set_hl(0, '@keyword.operator', { link = 'Operator' })
